name: push docker image to docker hub

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push cloud user
      uses: docker/build-push-action@v2
      with:
        context: ./react-admin
        file: ./react-admin/Dockerfile
        push: true
        tags: jast90/web-mall:latest